FROM daocloud.io/node:8.11.1

MAINTAINER yuliang <yu.liang@freelog.com>

RUN mkdir -p /data/freelog-node-web

WORKDIR /data/freelog-node-web

COPY . /data/freelog-node-web

RUN npm install

#ENV
#VOLUME ['/opt/logs','/opt/logs/db','/opt/logs/koa','/opt/logs/track']

ENV NODE_ENV prod
ENV EGG_SERVER_ENV prod
ENV PORT 7777

EXPOSE 7777

CMD [ "npm", "start" ]
