FROM daocloud.io/node:8.11.1

MAINTAINER yuliang <yu.liang@freelog.com>

RUN mkdir -p /data/freelog-node-web

WORKDIR /data/freelog-node-web

COPY . /data/freelog-node-web

RUN npm install

ENV NODE_ENV test
ENV EGG_SERVER_ENV test
ENV PORT 5777

EXPOSE 5777

CMD [ "npm", "start" ]
